name: Woke detect

on: [push]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        working-directory: ./example
        run: |
          npm ci

      - name: Detect
        uses: Ackee-Blockchain/woke-detect-pipeline@0.0.1
        with:
          working-directory: ./example
          compile-include-paths: "node_modules"
          export-sarif: true
        id: woke-detect

      - name: Upload SARIF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sarif-report
          path: ${{ steps.woke-detect.outputs.sarif }}

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.woke-detect.outputs.sarif }}